#!/bin/bash

OBJECTS=$(ip help 2>&1 | sed -e '/OBJECT *:= *{/,/}/!d;
                                 s/^.*{//;
                                 s/}.*$//' | awk 'BEGIN { RS="|" } { print $1 }' | sort -u)

LINKS=$(ip link help 2>&1 | sed -e '/TYPE *:= *{/,/}/!d;
                                    s/^.*{//;
                                    s/}.*$//' | awk 'BEGIN { RS="|" } { print $1 }' | sort -u)

(
printf "%s\n" "-Version"
ip -Version
printf '\n################################\n'

ip help 2>&1

for obj in $OBJECTS; do
        printf '\n################################\n'
        printf '%s\n\n' "$obj"
        ip $obj help 2>&1

        if [ "$obj" = "link" ]; then
                for lnk in $LINKS; do
                        printf '\n################################\n'
                        printf 'link add type %s help\n\n' "$lnk"
                        ip link add type $lnk help 2>&1
                done
        fi
done ) |

sed -e '
        /{/ {
            :a;
            /{[^}]*$/ {
                N;
                ba;
            }
            s/\n */ /g;
        }'
